#!/bin/bash

# |\___
# |O.o/
# (   )
#   U
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


CATREGEXP='(Meow(,? meow){0,4}[.?!] ){1,2}(Pur{2,3} (pur{2,3} ){0,2})?(\\^\\.\\^|:\\)|:D|:cat(2)?:|\\^\\^|:3)?'

STREAMID="0"
LOGIN="LOGIN-UUID"
CSRF="CSRF-TOKEN"
TENANTURL="TENANT-URL"
CHAT="false"
CHATID="0"

[[ -e "$DIR"/config.sh ]] && source "$DIR"/config.sh && echo "Config loaded."

print_usage(){
    echo "Usage: $0 [-m MEOWREGEX] [-p POSTTITLEREGEX] [-l LOGINTOKEN] [-c CSRFTOKEN] [-s STREAMID] [-t TENANTURL]"
}

DEBUG="false"
HTTPS="true"
while getopts 'h?duCI:m:l:c:s:t:p:' opt
do
    case "$opt" in
    h|\?)
        print_usage
        exit 0
        ;;
    m)
        CATREGEXP="$OPTARG"
        ;;
    l) 
        LOGIN="$OPTARG"
        ;;
    c)
        CSRF="$OPTARG"
        ;;
    s)
        STREAMID="$OPTARG"
        ;;
    t)
        TENANTURL="$OPTARG"
        ;;
    p)
        TITLEREGEXP="$OPTARG"
        ;;
    u)
        HTTPS="false"
        ;;
    C)
        CHAT="true"
        ;;
    I)
        CHATID="$OPTARG"
        ;;
    d)
        DEBUG="true"
        ;;
    esac
done

if [[ -z $TITLEREGEXP ]]
then
    TITLEREGEXP="$CATREGEXP"
fi

meow(){
node <<script
const RandExp = require('randexp');
const randexp = new RandExp('$1');
console.log(randexp.gen());
script
}

$DEBUG && {
echo CATREGEXP "$CATREGEXP"
echo LOGIN "$LOGIN"
echo CSRF "$CSRF"
echo STREAMID "$STREAMID"
echo TENANTURL "$TENANTURL"
echo TITLEREGEXP "$TITLEREGEXP"
echo HTTPS "$HTTPS"
echo DEBUG "$DEBUG"
}

CURLOPTS=(-H 'Cookie: login='"$LOGIN"'' -H 'Origin: http'$( $HTTPS && echo s )'://'"$TENANTURL"'' -H 'X-CSRF-Token: '"$CSRF"'' -H 'Accept-Language: en-US,en;q=0.9' -H 'Authorization: Cookie' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'X-BKPR-App-Name: app-web' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http'$( $HTTPS && echo s)'://'"$TENANTURL"'/stream/random')


sel=$(( RANDOM % 10 ))
num_img=1
exts=('dummy')

if ! $CHAT
then

    case "$sel" in
# Cat API
    0|1|2|3|4|6|7|8|9)
        num_img=$(( RANDOM % 4 % 3 + 1 ))
        for i in $( seq 1 $num_img )
        do
            echo "Downloading image..."
            IMAGEURL="$( curl $( $DEBUG || echo '-s') https://api.thecatapi.com/v1/images/search?format=json\&type=png\&api_key=MTQwMTIy | jq -r .[0].url )"
            ext="$( echo $IMAGEURL | sed -e 's/.*\.//' )"
            wget --quiet "$IMAGEURL" -O image$i."$ext"
            $DEBUG && echo "It's a $ext image!"
            exts+=("$ext")
        done
        ;;

# GaMERCaT
    30)
        echo "Today, I'll do a GaMERCaT post."
        while :
        do
            year="$( $DIR/webls http://thegamercat.com/wp-content/uploads/ | shuf -n 1 )"
            month="$( $DIR/webls "$year" | shuf -n 1 )"
            img="$( $DIR/webls "$month" | grep -P 'gamercat[^/]*\.(jpg|png|gif)' | grep -vP '\d\dx\d\d' | shuf -n 1 )"
            if [[ -n $img ]]
            then
                break
            fi
        done

        ext="$( echo $img | sed -e 's/.*\.//' )"
        wget -O image1.$ext -q $img
        exts+=("$ext")
        ;;
    5)
        echo "Let's do Business Cat today."
        while :
        do
            year="$( $DIR/webls http://www.businesscat.happyjar.com/wp-content/uploads/ | grep -P '\d\d\d\d' | shuf -n 1 )"
            month="$( $DIR/webls "$year" | shuf -n 1 )"
            img="$( $DIR/webls "$month" | grep -vP '\d\dx\d\d' | grep -vP '_...?(-.{1,4})?\.' | shuf -n 1 )"
            if [[ -n $img ]]
            then
                break
            fi
        done

        ext="$( echo $img | sed -e 's/.*\.//' )"
        wget -O image1.$ext -q $img
        exts+=("$ext")
        ;;
    esac

    echo "Uploading image..."
    for i in $( seq 1 $num_img )
    do
        $DEBUG && echo Uploading ${exts[$i]} image
        IMAGERESP="$( curl $( $DEBUG || echo '-s' ) 'http'$( $HTTPS && echo s)'://'"$TENANTURL"'/api/2/files' "${CURLOPTS[@]}" -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0AiRf8qodrGlBEb2' -F "file=@image$i.${exts[$i]};type=image/${exts[$i]}" )"
        $DEBUG && echo $IMAGERESP
        if [[ -z $IMAGELIST ]]
        then
            IMAGELIST="$IMAGERESP"
        else
            IMAGELIST="$IMAGELIST,$IMAGERESP"
        fi
    done

    $DEBUG && echo "Images list: $IMAGELIST"
fi

echo "Thinking of a witty post title..."
POSTTITLE="$(meow "$TITLEREGEXP")"
POSTTEXT="$(meow "$CATREGEXP")"
$DEBUG && echo $POSTTITLE
$DEBUG && echo $POSTTEXT

if $CHAT
then
    echo "Chatting..."

    POSTDATA='{"text":"'"$POSTTEXT"'","photos":[],"files":[],"uuid":"'"$(uuidgen)"'","conversationid":"'"$CHATID"'","byUser":true,"isEvent":false}'
    resp="$(curl $( $DEBUG || echo '-s') 'http'$( $HTTPS && echo s )'://'"$TENANTURL"'/api/2/conversations/'"$CHATID"'/messages' "${CURLOPTS[@]}" -H 'Content-Type: application/json' --data-binary "$POSTDATA" )"
    $DEBUG && echo "$resp"
else
    POSTDATA='{"id":null,"uuid":"'"$(uuidgen)"'","source":"beekeeper","created":"'"$(date -Is)"'","edited":null,"user_id":"61dcadf1-0297-430d-ab42-24fe42336202","name":"5","display_name":"Sir Fluffington","display_name_extension":null,"avatar":"https://d4up58j5h8ukq.cloudfront.net/ec4ef9f1-f54b-4e0a-8c98-afc9aa0a9033","comment_count":0,"comments":[],"liked_by_user":false,"sticky":false,"locked":false,"unread":false,"reported_by_user":false,"subscribed_by_user":false,"like_count":0,"anonymous":true,"report_count":0,"digest":0,"scheduled_at":null,"isPoll":false,"text":"'"$POSTTEXT"'","title":"'"$POSTTITLE"'","labels":[],"options":[],"streamid":'"$STREAMID"',"twitter":false,"facebook":false,"links":[],"status":"prepared","mentions":[],"mention_details":{},"media":['"$IMAGELIST"'],"byUser":true}'
    echo "Posting..."
    resp="$(curl $( $DEBUG || echo '-s') 'http'$( $HTTPS && echo s )'://'"$TENANTURL"'/api/2/posts' "${CURLOPTS[@]}" -H 'Content-Type: application/json' --data-binary "$POSTDATA" )"
    $DEBUG && echo "$resp"
fi

echo "Done!"
