#!/bin/bash

# |\___
# |O.o/
# (   )
#   U
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


CATREGEXP='(Meow(,? meow){0,4}[.?!] ){1,2}(Pur{2,3} (pur{2,3} ){0,2})?(\\^\\.\\^|:\\)|:D|:cat(2)?:|\\^\\^|:3)?'

STREAMID="0"
LOGIN="LOGIN-UUID"
TENANTURL="TENANT-URL"
CHAT="false"
CHATID="0"

[[ -e "$DIR"/config.sh ]] && source "$DIR"/config.sh && echo "Config loaded."

print_usage(){
    echo "Usage: $0 [-m MEOWREGEX] [-p POSTTITLEREGEX] [-l LOGINTOKEN] [-s STREAMID] [-t TENANTURL]"
}

DEBUG="false"
HTTPS="true"
while getopts 'h?duCI:m:l:c:s:t:p:' opt
do
    case "$opt" in
    h|\?)
        print_usage
        exit 0
        ;;
    m)
        CATREGEXP="$OPTARG"
        ;;
    l) 
        LOGIN="$OPTARG"
        ;;
    s)
        STREAMID="$OPTARG"
        ;;
    t)
        TENANTURL="$OPTARG"
        ;;
    p)
        TITLEREGEXP="$OPTARG"
        ;;
    u)
        HTTPS="false"
        ;;
    C)
        CHAT="true"
        ;;
    I)
        CHATID="$OPTARG"
        ;;
    d)
        DEBUG="true"
        ;;
    esac
done

if [[ -z $TITLEREGEXP ]]
then
    TITLEREGEXP="$CATREGEXP"
fi

meow(){
node <<script
const RandExp = require('randexp');
const randexp = new RandExp('$1');
console.log(randexp.gen());
script
}

$DEBUG && {
echo CATREGEXP "$CATREGEXP"
echo LOGIN "$LOGIN"
echo STREAMID "$STREAMID"
echo TENANTURL "$TENANTURL"
echo TITLEREGEXP "$TITLEREGEXP"
echo HTTPS "$HTTPS"
echo DEBUG "$DEBUG"
}

CURLOPTS=(-H 'Authorization: Token '"$LOGIN"'' -H 'Origin: http'$( $HTTPS && echo s )'://'"$TENANTURL"'' -H 'Accept-Language: en-US,en;q=0.9' -H 'Accept: application/json')


sel=$(( RANDOM % 10 ))
num_img=1
exts=('dummy')

if ! $CHAT
then

    case "$sel" in
# Cat API
    0|1|2|3|4|5|6|7|8|9)
        num_img=$(( RANDOM % 4 % 3 + 1 ))
        for i in $( seq 1 $num_img )
        do
            echo "Downloading image..."
            IMAGEURL="$( curl $( $DEBUG || echo '-s') https://api.thecatapi.com/v1/images/search?format=json\&type=png\&api_key=MTQwMTIy | jq -r .[0].url )"
            ext="$( echo $IMAGEURL | sed -e 's/.*\.//' )"
            wget --quiet "$IMAGEURL" -O image$i."$ext"
            $DEBUG && echo "It's a $ext image!"
            exts+=("$ext")
        done
        ;;

# GaMERCaT
    30)
        echo "Today, I'll do a GaMERCaT post."
        while :
        do
            year="$( $DIR/webls http://thegamercat.com/wp-content/uploads/ | shuf -n 1 )"
            month="$( $DIR/webls "$year" | shuf -n 1 )"
            img="$( $DIR/webls "$month" | grep -P 'gamercat[^/]*\.(jpg|png|gif)' | grep -vP '\d\dx\d\d' | shuf -n 1 )"
            if [[ -n $img ]]
            then
                break
            fi
        done

        ext="$( echo $img | sed -e 's/.*\.//' )"
        wget -O image1.$ext -q $img
        exts+=("$ext")
        ;;
    50)
        echo "Let's do Business Cat today."
        while :
        do
            year="$( $DIR/webls http://www.businesscat.happyjar.com/wp-content/uploads/ | grep -P '\d\d\d\d' | shuf -n 1 )"
            month="$( $DIR/webls "$year" | shuf -n 1 )"
            img="$( $DIR/webls "$month" | grep -vP '\d\dx\d\d' | grep -vP '_...?(-.{1,4})?\.' | shuf -n 1 )"
            if [[ -n $img ]]
            then
                break
            fi
        done

        ext="$( echo $img | sed -e 's/.*\.//' )"
        wget -O image1.$ext -q $img
        exts+=("$ext")
        ;;
    esac

    echo "Uploading image..."
    for i in $( seq 1 $num_img )
    do
        $DEBUG && echo Uploading ${exts[$i]} image
        IMAGERESP="$( curl $( $DEBUG || echo '-s' ) 'http'$( $HTTPS && echo s)'://'"$TENANTURL"'/api/2/files' "${CURLOPTS[@]}" -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0AiRf8qodrGlBEb2' -F "file=@image$i.${exts[$i]};type=image/${exts[$i]}" )"
        $DEBUG && echo $IMAGERESP
        if [[ -z $IMAGELIST ]]
        then
            IMAGELIST="$IMAGERESP"
        else
            IMAGELIST="$IMAGELIST,$IMAGERESP"
        fi
    done

    $DEBUG && echo "Images list: $IMAGELIST"
fi

echo "Thinking of a witty post title..."
POSTTITLE="$(meow "$TITLEREGEXP")"
POSTTEXT="$(meow "$CATREGEXP")"
$DEBUG && echo $POSTTITLE
$DEBUG && echo $POSTTEXT

if $CHAT
then
    echo "Chatting..."

    POSTDATA='{"text":"'"$POSTTEXT"'","media":[],"files":[],"uuid":"'"$(uuidgen)"'","conversationid":"'"$CHATID"'"}'
    resp="$(curl $( $DEBUG || echo '-s') 'http'$( $HTTPS && echo s )'://'"$TENANTURL"'/api/2/conversations/'"$CHATID"'/messages' "${CURLOPTS[@]}" -H 'Content-Type: application/json' --data-binary "$POSTDATA" )"
    $DEBUG && echo "$resp"
else
    POSTDATA='{"text":"'"$POSTTEXT"'","title":"'"$POSTTITLE"'","labels":[],"options":[],"streamid":'"$STREAMID"',"links":[],"media":['"$IMAGELIST"']}'
    echo "Posting..."
    resp="$(curl $( $DEBUG || echo '-s') 'http'$( $HTTPS && echo s )'://'"$TENANTURL"'/api/2/posts' "${CURLOPTS[@]}" -H 'Content-Type: application/json' --data-binary "$POSTDATA" )"
    $DEBUG && echo "$resp"
fi

echo "Done!"
