#!/bin/bash

# |\___
# |O.o/
# (   )
#   U

DEFAULTCATREGEXP='(Meow(,? meow){0,7}[.?!] ){1,3}(Pur{2,5} (pur{2,5} ){0,2})?(\\^\\.\\^|:\\)|:D|:cat(2)?:|\\^\\^|:3)?'
CATREGEXP="${1:-$DEFAULTCATREGEXP}"

node <<script
const RandExp = require('randexp');
const randexp = new RandExp('$CATREGEXP');
console.log(randexp.gen());
script
